let constants = {
	ADD_EMPLOYEE: 'ADD_EMPLOYEE',
	REMOVE_EMPLOYEE: 'REMOVE_EMPLOYEE',
	GITHUB_FETCH_STARTED: 'GITHUB_FETCH_STARTED',
	GITHUB_GOT_REPONSE_SUCCESS: 'GITHUB_GOT_REPONSE_SUCCESS',
	GITHUB_GOT_REPONSE_FAILURE: 'GITHUB_GOT_REPONSE_FAILURE'
};
export default constants